apiVersion: v1
data:
  clowder_config.json: |-
    {
        "features": {
            "createServiceMonitor": true,
            "watchStrimziResources": true,
            "enableKedaResources": true,
            "reconciliationMetrics": true,
            "enableExternalStrimzi": true,
            "disableStrimziFinalizer": true
        }
    }
kind: ConfigMap
metadata:
  name: clowder-config
