apiVersion: v1
data:
  clowder_config.json: |-
    {
        "features": {
            "createServiceMonitor": true,
            "watchStrimziResources": true
        }
    }
kind: ConfigMap
metadata:
  name: clowder-config
