
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: kafkas.kafka.strimzi.io
spec:
  group: kafka.strimzi.io
  names:
    kind: Kafka
    listKind: KafkaList
    plural: kafkas
    singular: kafka
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Kafka is the Schema for the kafkatopics API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        status:
          description: KafkaTopicStatus defines the observed state of KafkaTopic
          properties:
            conditions:
              description: A list of k8s Conditions.
              items:
                properties:
                  lastTransitionTime:
                    description: The last transition time of the resource.
                    type: string
                  message:
                    description: The message of the last transition.
                    type: string
                  reason:
                    description: The Reason for hte transition change.
                    type: string
                  status:
                    description: The status of the condition.
                    type: string
                  type:
                    description: The type of the condition.
                    type: string
                type: object
              type: array
            listeners:
              description: A list of KafkaListener objects.
              items:
                description: KafkaListener represents a configured Kafka listener instance.
                properties:
                  addresses:
                    description: A list of addresses that the Kafka instance is listening on.
                    items:
                      description: Address struct represents the physical connection details of a Kafka Server.
                      properties:
                        host:
                          description: Host defines the hostname of the Kafka server.
                          type: string
                        port:
                          description: Port defines the port of the Kafka server.
                          format: int32
                          type: integer
                      type: object
                    type: array
                  bootstrapServers:
                    description: A bootstrap server that the Kafka client can initially conenct to.
                    type: string
                  certificates:
                    description: A list of certificates to be used with this Kafka instance.
                    items:
                      type: string
                    type: array
                  type:
                    description: The Kafka server type.
                    type: string
                type: object
              type: array
            observedGeneration:
              description: The observed generation of the Kafka resource.
              format: int32
              type: integer
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
